chef:
    server:
        install_script: https://raw.github.com/rcbops-qa/monster/master/files/install-chef-server.sh
        install_dir: /opt/rcbops
        upgrade_dir: /opt/upgrade
    client:
        version: 11.08.0
        run_cmd: "chef-client"
environments:
    openssh:
        server:
            subsystem: "sftp internal-sftp"
    package_component:
        default: havana
    keystone:
        default:
            admin_user: admin
            users:
                demo:
                    roles:
                        Member:
                          - demo
                    default_tenant: demo
                    password: secrete
                demo2:
                    roles:
                        Member:
                          - demo2
                    default_tenant: demo2
                    password: secrete
                admin:
                    roles:
                        admin:
                            - admin
                    default_tenant: admin
                    password: secrete
            tenants:
                - admin
                - service
                - demo
                - demo2
    monitoring:
        default:
            procmon_provider: monit
    mysql:
        default:
            root_network_acl: "%"
            allow_remote_root: true
    nova:
        razor2:
            apply_patches: false
            networks:
                public:
                    bridge: br0
                    dns1: 8.8.8.8
                    dns2: 8.8.4.4
                    bridge_dev: vmnet
                    network_size: "30"
                    ipv4_cidr: 10.127.102.0/27
                    label: public
            libvirt:
                virt_type: kvm
    osops:
        default:
            apply_patches: true
    horizon:
        neutron:
          enable_lb: true
          theme: default
        default:
            theme: default
    developer_mode:
        default:
            default: false
    osops_networks:
        management: 10.127.101.0/24
        nova: 10.127.101.0/24
        public: 10.127.101.0/24
    glance:
        default:
            image_upload: true
            images:
                - cirros
                - precise
    neutron:
        neutron:
            lbaas:
                enabled: true
            ovs:
                network_type: gre
                vlans: 864
    cinder:
        local:
            storage:
                provider: lvm
                lvm:
                    volume_group: vg_storage
    vips:
        mysql-db: 10.127.101.68
        rabbitmq-queue: 10.127.101.69
        cinder-api: 10.127.101.70
        glance-api: 10.127.101.70
        glance-registry: 10.127.101.70
        horizon-dash: 10.127.101.70
        horizon-dash_ssl: 10.127.101.70
        keystone-admin-api: 10.127.101.70
        keystone-internal-api: 10.127.101.70
        keystone-service-api: 10.127.101.70
        nova-api: 10.127.101.70
        nova-ec2-public: 10.127.101.70
        nova-api-metadata: 10.127.101.70
        nova-novnc-proxy: 10.127.101.70
        nova-xvpvnc-proxy: 10.127.101.70
        neutron-api: 10.127.101.70
        swift-proxy: 10.127.101.70
        ceilometer-api: 10.127.101.70
        ceilometer-central-agent: 10.127.101.70
        heat-api: 10.127.101.70
        heat-api-cfn: 10.127.101.70
        heat-api-cloudwatch: 10.127.101.70
        config:
            10.127.101.68:
                vrid: 14
                network: public
            10.127.101.69:
                vrid: 15
                network: public
            10.127.101.70:
                vrid: 16
                network: public
rcbops:
    retrofit:
        supported:
            os:
                - ubuntu
        git:
            url: https://github.com/Apsu/retrofit.git
            branches:
                - master
                - dev
    compute:
        kernel:
          centos:
            image: ce44b9c0-bb94-4fac-a7df-99b6aeab4c57
            version: 2.6.32-358.123.2.openstack.el6.x86_64
            install: rpm -Uvh http://repos.fedorapeople.org/repos/openstack/openstack-grizzly/epel-6/kernel-2.6.32-358.123.2.openstack.el6.x86_64.rpm http://repos.fedorapeople.org/repos/openstack/openstack-grizzly/epel-6/kernel-firmware-2.6.32-358.123.2.openstack.el6.noarch.rpm http://repos.fedorapeople.org/repos/openstack/openstack-grizzly/epel-6/kernel-headers-2.6.32-358.123.2.openstack.el6.x86_64.rpm
        git:
            url: https://github.com/rcbops/chef-cookbooks.git
            branches:
                havana:
                    - v4.2.2rc
                    - v4.2.2
                    - v4.2.1
                    - v4.2.0
                grizzly:
                    - v4.1.5rc
                    - v4.1.4rc
                    - v4.1.3
                    - v4.1.2
                    - v4.1.1
                    - v4.1.0
                    - v4.0.0
                folsom:
                    - v3.0.0
                    - v3.0.1
                    - v3.1.0
        chefserver:
            run_list: []
        compute:
            run_list: ['role[single-compute]']
        ldap:
            run_list: ['role[qa-openldap]']
        controller1:
            run_list: ['role[ha-controller1]']
        controller2:
            run_list: ['role[ha-controller2]']
        cinder:
            run_list: ['role[cinder-volume]']
        network:
            run_list: ['role[single-network-node]']
        tempest:
            run_list: ['recipe[tempest]']
        orchestration1:
            run_list: ['role[heat-all]']
        orchestration2:
            run_list: ['role[heat-api]',
                       'role[heat-api-cfn]',
                       'role[heat-api-cloudwatch]']
        networkmanager:
            run_list: ['role[quantum-network-manager]']
        metrics:
            controller:
                run_list: ['role[ceilometer-setup]',
                           'role[ceilometer-api]',
                           'role[ceilometer-central-agent]',
                           'role[ceilometer-collector]']
            compute:
                run_list: ['role[ceilometer-compute]']
    storage:
        git:
            url: https://github.com/rcbops-cookbooks/swift-private-cloud.git
            branches:
                master:
                    tags:
                        - v4.2.0
        chefserver:
            run_list: []
        controller1:
            run_list: ['role[spc-starter-controller]']
        proxy:
            run_list: ['role[spc-starter-proxy]']
        storage:
            run_list: ['role[spc-starter-storage]']
tests:
  tempest:
    repo: https://github.com/openstack/tempest.git
    dir: "/opt/tempest"
    test_map:
      glance:
        - image
        - compute/images
      nova:
        - compute
      keystone:
        - compute/admin
        - compute/security_groups
        - compute/test_authorization.py
        - identity
      neutron:
        - network
      cinder:
        - compute/volumes
        - volume
      swift:
        - object_storage

razor2:
    network:
        vmnet:
            cidr: 10.127.102.0/27
            iface: vmnet
        mgmt:
            cidr: 10.127.101.32/27
            iface: mgmt

upgrade:
  commands:
    backup-db: bash <(curl -s https://raw.github.com/rcbops/support-tools/master/havana-tools/database_backup.sh)
    restore-db: bash <(curl -s https://raw.github.com/rcbops/support-tools/master/havana-tools/quantum-upgrade.sh)
    stop-services: for i in `monit status | grep Process | awk '{print $2}' | grep -v mysql | sed "s/'//g"`; do monit stop $i; done; service keepalived stop
    start-services: for i in `monit status | grep Process | awk '{print $2}' | grep -v mysql | sed "s/'//g"`; do monit start $i; done; service keepalived restart
  supported:
    v4.1.2:
      - v4.1.3rc
      - v4.1.3
      - v4.1.4rc
      - v4.1.4
      - v4.1.5rc
      - v4.1.5
    v4.1.3:
      - v4.1.4rc
      - v4.1.4
      - v4.2.1rc
      - v4.2.1
      - v4.2.2rc
      - v4.2.2
      - v4.1.5rc
      - v4.1.5
    v4.1.4:
      - v4.1.5rc
      - v4.1.5
      - v4.2.1rc
      - v4.2.1
      - v4.2.2rc
      - v4.2.2
    v4.1.5:
      - v4.2.2rc
      - v4.2.2
    v4.2.1:
      - v4.2.2rc
      - v4.2.2
    v4.2.2rc:
      - v4.2.3rc
      - v4.2.3
